In [65]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import pickle

In [6]:
df = pd.read_csv("/content/drive/MyDrive/diabetes_dataset/diabetes_dataset.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [29]:
df.shape

(768, 9)

In [8]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [10]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [11]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
# Outcome unique value counts
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [15]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

smote = SMOTE(sampling_strategy='minority', random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print("Before SMOTE:\n", y.value_counts())
print("After SMOTE:\n", y_resampled.value_counts())

Before SMOTE:
 Outcome
0    500
1    268
Name: count, dtype: int64
After SMOTE:
 Outcome
1    500
0    500
Name: count, dtype: int64


In [16]:
df['Outcome'].unique()

array([1, 0])

In [26]:
df.groupby('Outcome')

In [27]:
df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [31]:
X_resampled.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [18]:
y_resampled.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

Data Standardization

In [19]:
std_scale = StandardScaler()

In [32]:
std_scale.fit(X_resampled)

StandardScaler()

In [33]:
standardized_data =std_scale.transform(X_resampled)

In [34]:
standardized_data

array([[ 0.63294236,  0.70459938,  0.14812026, ...,  0.12159194,
         0.38498862,  1.41593023],
       [-0.88563336, -1.26050581, -0.15488743, ..., -0.8112318 ,
        -0.43879908, -0.26234016],
       [ 1.24037265,  1.79632449, -0.25589   , ..., -1.25099156,
         0.51930183, -0.17401014],
       ...,
       [ 0.02551207,  1.42201874,  0.70363436, ...,  0.08161378,
         2.08429804,  1.50426025],
       [ 1.24037265, -0.44951002,  0.6026318 , ...,  0.19796319,
        -0.63798181,  0.09097992],
       [ 0.02551207,  0.5798308 ,  0.50162923, ...,  0.63175999,
         0.21475525,  0.4443    ]])

In [35]:
X = standardized_data
Y = df['Outcome']

In [36]:
X

array([[ 0.63294236,  0.70459938,  0.14812026, ...,  0.12159194,
         0.38498862,  1.41593023],
       [-0.88563336, -1.26050581, -0.15488743, ..., -0.8112318 ,
        -0.43879908, -0.26234016],
       [ 1.24037265,  1.79632449, -0.25589   , ..., -1.25099156,
         0.51930183, -0.17401014],
       ...,
       [ 0.02551207,  1.42201874,  0.70363436, ...,  0.08161378,
         2.08429804,  1.50426025],
       [ 1.24037265, -0.44951002,  0.6026318 , ...,  0.19796319,
        -0.63798181,  0.09097992],
       [ 0.02551207,  0.5798308 ,  0.50162923, ...,  0.63175999,
         0.21475525,  0.4443    ]])

In [39]:
# Choosing Logistic Regression

lg = LogisticRegression(max_iter=500)

lg.fit(X_resampled,y_resampled)

# Predict with training data
lg_predict = lg.predict(X_resampled)

#Accuracy Score for Training data
lg_accuracy = accuracy_score(lg_predict, y_resampled)
print("The accuracy score for training data is : ", lg_accuracy)

The accuracy score for training data is :  0.751


In [41]:
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, stratify=y_resampled,random_state=2)

Training Model

In [42]:
classifier  = svm.SVC(kernel="linear")

In [43]:
classifier.fit(X_train,y_train)

SVC(kernel='linear')

In [44]:
X_train_prediction = classifier.predict(X_train)

In [45]:
X_train_prediction

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,

In [46]:
# Accuracy score for training data
X_train_accuracy =accuracy_score(X_train_prediction,y_train)

In [47]:
print("Accuracy score for training data: " , X_train_accuracy)

Accuracy score for training data:  0.755


In [48]:
# predict for the testing data
X_test_predict = classifier.predict(X_test)
X_test_predict

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1])

In [49]:
X_test_accuracy = accuracy_score(X_test_predict,y_test)

In [50]:
print("Accuracy Score for Testing Data: ", X_test_accuracy)

Accuracy Score for Testing Data:  0.705


Make a Predictive System to predict whether a person is diabetic or not

In [63]:
feature_columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
                   "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]
input = (10,168,74,0,0,38,0.537,34)

input_df = pd.DataFrame([input], columns=feature_columns)

std_data = std_scale.transform(input_df)
print(std_data)

[[ 1.84780294  1.3284423   0.24912282 -1.30197843 -0.71924071  0.70793829
   0.1163622   0.0026499 ]]


In [58]:
prediction = classifier.predict(std_data)
prediction

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [59]:
#print message as diabetic or not
if (prediction[0] == 0):
    print("Assessment shows no diabetes risk.")
else:
    print("Assessment indicates potential diabetes risk.")

Assessment shows no diabetes risk.


Choosing a RandomForest Classifier

In [60]:

rf_classifier = RandomForestClassifier()
#fit the model
rf_classifier.fit(X_train,y_train)

# Predict with training data
rf_train_predict = rf_classifier.predict(X_train)

#Accuracy Score for Training data
rf_train_accuracy = accuracy_score(y_train, rf_train_predict)
print("The accuracy Score for Training Data : " , rf_train_accuracy)

# Predict with testing data
rf_test_predict = rf_classifier.predict(X_test)

#Accuracy Score for Testing data
rf_test_accuracy = accuracy_score(y_test, rf_test_predict)
print("The accuracy Score for Testing Data : " , rf_test_accuracy)

The accuracy Score for Training Data :  1.0
The accuracy Score for Testing Data :  0.83


In [62]:
# Choosing Logistic Regression

lg_reg = LogisticRegression(max_iter=500)

lg_reg.fit(X_train, y_train)

# Predict with training data
lg_reg_train_predict = lg_reg.predict(X_train)

# Accuracy Score for Training data (corrected order)
lg_reg_train_accuracy = accuracy_score(y_train, lg_reg_train_predict)
print("The accuracy score for Training data is : ", lg_reg_train_accuracy)

# Predict with testing data
lg_reg_test_predict = lg_reg.predict(X_test)

# Accuracy Score for Testing data
lg_reg_test_accuracy = accuracy_score(y_test, lg_reg_test_predict)
print("The accuracy score for Testing data is : ", lg_reg_test_accuracy)

The accuracy score for Training data is :  0.75625
The accuracy score for Testing data is :  0.74


In [66]:
# Save the model

#save the model as pickle file
pickle.dump(lg_reg,open('diabetes_model_1.pkl','wb'))

#save standard scaler
pickle.dump(std_scale,open('diabetes_std_scaler_model_1.pkl','wb'))